language: java
jdk:
   - openjdk8
script: mvn clean install
cache:
  directories:
  - $HOME/.m2

services:
  - docker
sudo: required
deploy:
  provider: script
  script: bash deploy.sh
  on:
branch: master
