language: java
jdk:
   - openjdk8
script: mvn clean install
cache:
  directories:
  - $HOME/.m2

sudo: required
services:
  - docker
script:
  - docker build -t myapp .
after_success:
  - pip install --user awscli # install aws cli w/o sudo
  - export PATH=$PATH:$HOME/.local/bin
  - sudo add-apt-repository ppa:eugenesan/ppa -y
  - sudo apt-get update
  - sudo apt-get install jq -y
  - jq --version
  - aws --version
  - curl https://raw.githubusercontent.com/silinternational/ecs-deploy/master/ecs-deploy | sudo tee -a /usr/bin/ecs-deploy
  - sudo chmod +x /usr/bin/ecs-deploy
  - eval $(aws ecr get-login --no-include-email --region us-east-1)
  - docker tag myapp $IMAGE_REPO_URL:latest
