language: java
jdk:
   - openjdk8
script: mvn clean install
cache:
  directories:
  - $HOME/.m2

sudo: required
services:
  - docker
script:
  - docker build -t front .
after_success:
  - docker --version
