language: java
jdk:
   - openjdk8
script: mvn clean install
cache:
  directories:
  - $HOME/.m2

sudo: required
services:
  - docker

deploy:
  provider: script
  script: bash deploy.sh
  on:
branch: master
