language: java
jdk:
   - openjdk8
script: mvn clean install
cache:
  directories:
  - $HOME/.m2

sudo: required
services:
  - docker
script:
  - docker build -t front .
after_success:
  - docker --version
  - pip install --user awscli
  - `aws ecr get-login --no-include-email --region ${REGION}`
